### ISSUE TITLE
问下yar-server-java估计什么时候能出现?

### ISSUE THREAD

**Issue by ghost** [zhoumengkang/yar-java-client#2]
问下yar-server-java估计什么时候能出现?

**Comment by zhoumengkang** [comment]
其实这只是对鸟哥 yar 的 java 客户端的封装。我当时写是这个项目是的情况是运营跟换运营规则太频繁，我需要把运营规则独立出来服务化，供其他服务调用。
我写这个项目的初衷 https://mengkang.net/580.html
